export const ROUTES = {
  login: '/login',
  dashboard: '/dashboard',
  tickets: '/dashboard/tickets',
  ticketDetails: (id: string) => `/dashboard/tickets/${id}` as const,
  notifications: '/dashboard/notifications',
  profile: '/dashboard/profile',
  users: '/dashboard/users',
  supports: '/dashboard/supports',
  supportAdd: '/dashboard/supports/add',
  supportDetails: (id: string | number) => `/dashboard/supports/${id}` as const,
  departments: '/dashboard/departments',
  reports: '/dashboard/reports',
  unauthorized: '/dashboard/unauthorized',
} as const;
